### ISSUE TITLE
prop6

### ISSUE THREAD

**Issue by hershaw** [LDSSA/infrastructure#1]
https://github.com/LDSSA/sa-infra/blob/master/proposals/prop6.md

Please read it and leave your comments here! This one would be very good for multiple people to check out because once we make these decisions, we are stuck with them! No going back! #YOLO!

**Comment by hershaw** [comment]
Chi says: 

The Submissions repo should be similar to the Students repo (and not to the Instructors repo, as it says in the document), right?

**Comment by hershaw** [comment]
Hugo says:

The submission repo will be an empty skeleton with a directory structure. So the structure will be the same as both of them.
I'll change it to make it more clear.
Thanks

**Comment by Juliana-R** [comment]
📜 This issue has gone > 2 years without activity, and will therefore be closed. Please reopen if necessary.
